// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGfIIWVPnPC9RCbUUZGET5drd3rzxWYI8',
    appId: '1:839325859921:web:378af05d4839efc9a2f870',
    messagingSenderId: '839325859921',
    projectId: 'tranquility-7f5bd',
    authDomain: 'tranquility-7f5bd.firebaseapp.com',
    storageBucket: 'tranquility-7f5bd.appspot.com',
    measurementId: 'G-QDY8NF76B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeP6zF3_8v2DZiSUxUiduYa1mFIeUgFyg',
    appId: '1:839325859921:android:c2bb3659346769fda2f870',
    messagingSenderId: '839325859921',
    projectId: 'tranquility-7f5bd',
    storageBucket: 'tranquility-7f5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMzPCoWs2Pv2YF6X5oIh8hF0cEaFg8e4',
    appId: '1:839325859921:ios:06bf34df7ee7c30ba2f870',
    messagingSenderId: '839325859921',
    projectId: 'tranquility-7f5bd',
    storageBucket: 'tranquility-7f5bd.appspot.com',
    iosClientId: '839325859921-rlk19gpq1ke2qnsrd0lb471t6gnamgio.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabak26CapitalsUi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMzPCoWs2Pv2YF6X5oIh8hF0cEaFg8e4',
    appId: '1:839325859921:ios:744ce4bc737f9bbba2f870',
    messagingSenderId: '839325859921',
    projectId: 'tranquility-7f5bd',
    storageBucket: 'tranquility-7f5bd.appspot.com',
    iosClientId: '839325859921-9oau4ndrb1sfivuq1e866goacbu4v4dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabak26CapitalsUi1.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGfIIWVPnPC9RCbUUZGET5drd3rzxWYI8',
    appId: '1:839325859921:web:64483a706a55ba12a2f870',
    messagingSenderId: '839325859921',
    projectId: 'tranquility-7f5bd',
    authDomain: 'tranquility-7f5bd.firebaseapp.com',
    storageBucket: 'tranquility-7f5bd.appspot.com',
    measurementId: 'G-6CW0MJ783X',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCGfIIWVPnPC9RCbUUZGET5drd3rzxWYI8',
    appId: '1:839325859921:web:14ca0e7d5e3e30c8a2f870',
    messagingSenderId: '839325859921',
    projectId: 'tranquility-7f5bd',
    authDomain: 'tranquility-7f5bd.firebaseapp.com',
    storageBucket: 'tranquility-7f5bd.appspot.com',
    measurementId: 'G-WFCXDHZTCC',
  );
}
